/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";
  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });
  document.body.appendChild(btn);
}

function createStartOverlay() {
  const overlay = document.createElement("div");
  overlay.className = "start-overlay";
  overlay.innerHTML = '<button class="start-btn" type="button">开启</button>';
  document.body.appendChild(overlay);
  return overlay;
}

function safePlay(audio) {
  if (!audio || !audio.querySelector("source")?.src) {
    return Promise.resolve(false);
  }

  return audio.play()
    .then(() => true)
    .catch((err) => {
      console.warn("Music playback skipped:", err.message);
      return false;
    });
}

function resetAudio(audio, shouldPlay) {
  if (!audio) return;

  audio.pause();
  try {
    audio.currentTime = 0;
  } catch (err) {
    console.warn("Music reset skipped:", err.message);
  }

  if (shouldPlay) safePlay(audio);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();
  const startOverlay = createStartOverlay();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  if (!window.gsap) {
    console.error("GSAP is required but was not loaded.");
    return;
  }

  const tl = buildTimeline(rendered, audio);
  const startBtn = startOverlay.querySelector(".start-btn");
  startBtn.addEventListener("click", () => {
    startBtn.disabled = true;
    safePlay(audio);
    startOverlay.classList.add("is-hidden");
    tl.restart(true);
  });
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered, audio) {
  const tl = gsap.timeline({ paused: true });

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  // Track deferred exits for overlay components
  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    // Flush deferred exits before non-overlay sections
    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    // Animate
    tl.set(el, { visibility: "visible" });
    comp.animate(tl, el, CONFIG);

    // Handle exit lifecycle
    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  // Flush remaining
  deferredExits.forEach((fn) => fn());

  // Setup replay
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => {
      gsap.set(replayBtn, { pointerEvents: "none" });
      resetAudio(audio, true);
      tl.restart(true);
    });
  }

  return tl;
}
